// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-xIvBzS4kJY2ZU3m24XzCjyiTMizDmD0',
    appId: '1:959088467303:web:1e3e039fe6252a0cc623c2',
    messagingSenderId: '959088467303',
    projectId: 'instagram-clone-799f4',
    authDomain: 'instagram-clone-799f4.firebaseapp.com',
    storageBucket: 'instagram-clone-799f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4QL9Xgxh6k5zOLC9l13M17pArPtG_bDw',
    appId: '1:959088467303:android:024377c3264a366ac623c2',
    messagingSenderId: '959088467303',
    projectId: 'instagram-clone-799f4',
    storageBucket: 'instagram-clone-799f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wyBi8NgKyGNt1J6t4_7sHOBKmMNhemc',
    appId: '1:959088467303:ios:9550d9c30c7ccdfcc623c2',
    messagingSenderId: '959088467303',
    projectId: 'instagram-clone-799f4',
    storageBucket: 'instagram-clone-799f4.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-wyBi8NgKyGNt1J6t4_7sHOBKmMNhemc',
    appId: '1:959088467303:ios:9550d9c30c7ccdfcc623c2',
    messagingSenderId: '959088467303',
    projectId: 'instagram-clone-799f4',
    storageBucket: 'instagram-clone-799f4.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-xIvBzS4kJY2ZU3m24XzCjyiTMizDmD0',
    appId: '1:959088467303:web:afc4905bd30c6b09c623c2',
    messagingSenderId: '959088467303',
    projectId: 'instagram-clone-799f4',
    authDomain: 'instagram-clone-799f4.firebaseapp.com',
    storageBucket: 'instagram-clone-799f4.appspot.com',
  );
}
